/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MemoryRegistry {
  export type MemoryStruct = {
    creator: AddressLike;
    timestamp: BigNumberish;
    latitudeE7: BigNumberish;
    longitudeE7: BigNumberish;
    isPublic: boolean;
    title: string;
    note: string;
  };

  export type MemoryStructOutput = [
    creator: string,
    timestamp: bigint,
    latitudeE7: bigint,
    longitudeE7: bigint,
    isPublic: boolean,
    title: string,
    note: string
  ] & {
    creator: string;
    timestamp: bigint;
    latitudeE7: bigint;
    longitudeE7: bigint;
    isPublic: boolean;
    title: string;
    note: string;
  };
}

export interface MemoryRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getMemory" | "mintMemory" | "nextMemoryId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MemoryMinted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMemory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintMemory",
    values: [string, string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMemoryId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getMemory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintMemory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMemoryId",
    data: BytesLike
  ): Result;
}

export namespace MemoryMintedEvent {
  export type InputTuple = [
    memoryId: BigNumberish,
    creator: AddressLike,
    timestamp: BigNumberish,
    latitudeE7: BigNumberish,
    longitudeE7: BigNumberish,
    isPublic: boolean,
    title: string,
    note: string
  ];
  export type OutputTuple = [
    memoryId: bigint,
    creator: string,
    timestamp: bigint,
    latitudeE7: bigint,
    longitudeE7: bigint,
    isPublic: boolean,
    title: string,
    note: string
  ];
  export interface OutputObject {
    memoryId: bigint;
    creator: string;
    timestamp: bigint;
    latitudeE7: bigint;
    longitudeE7: bigint;
    isPublic: boolean;
    title: string;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemoryRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MemoryRegistry;
  waitForDeployment(): Promise<this>;

  interface: MemoryRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMemory: TypedContractMethod<
    [memoryId: BigNumberish],
    [MemoryRegistry.MemoryStructOutput],
    "view"
  >;

  mintMemory: TypedContractMethod<
    [
      title: string,
      note: string,
      latitudeE7: BigNumberish,
      longitudeE7: BigNumberish,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  nextMemoryId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMemory"
  ): TypedContractMethod<
    [memoryId: BigNumberish],
    [MemoryRegistry.MemoryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintMemory"
  ): TypedContractMethod<
    [
      title: string,
      note: string,
      latitudeE7: BigNumberish,
      longitudeE7: BigNumberish,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextMemoryId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MemoryMinted"
  ): TypedContractEvent<
    MemoryMintedEvent.InputTuple,
    MemoryMintedEvent.OutputTuple,
    MemoryMintedEvent.OutputObject
  >;

  filters: {
    "MemoryMinted(uint256,address,uint64,int64,int64,bool,string,string)": TypedContractEvent<
      MemoryMintedEvent.InputTuple,
      MemoryMintedEvent.OutputTuple,
      MemoryMintedEvent.OutputObject
    >;
    MemoryMinted: TypedContractEvent<
      MemoryMintedEvent.InputTuple,
      MemoryMintedEvent.OutputTuple,
      MemoryMintedEvent.OutputObject
    >;
  };
}
